/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ullink_jni_femas_wrapper_Session */

#ifndef _Included_com_ullink_jni_femas_wrapper_Session
#define _Included_com_ullink_jni_femas_wrapper_Session
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ullink_jni_femas_wrapper_Session
 * Method:    femasInitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ullink_jni_femas_wrapper_Session_femasInitialize
  (JNIEnv *, jclass);

/*
 * Class:     com_ullink_jni_femas_wrapper_Session
 * Method:    femasDispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ullink_jni_femas_wrapper_Session_femasDispose
  (JNIEnv *, jclass);

/*
 * Class:     com_ullink_jni_femas_wrapper_Session
 * Method:    femasLoginEx
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_ullink_jni_femas_wrapper_Session_femasLoginEx
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jboolean);

/*
 * Class:     com_ullink_jni_femas_wrapper_Session
 * Method:    femasLogoutEx
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ullink_jni_femas_wrapper_Session_femasLogoutEx
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_ullink_jni_femas_wrapper_Session
 * Method:    femasQryInstrument
 * Signature: (Lcom/ullink/jni/femas/wrapper/struct/CUstpFtdcQryInstrumentField;I)I
 */
JNIEXPORT jint JNICALL Java_com_ullink_jni_femas_wrapper_Session_femasQryInstrument
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
